python3 visualize.py bmcite
python3 visualize.py liu
python3 visualize.py sim1
python3 visualize.py sim2
python3 visualize.py sim3
python3 visualize.py sim4
python3 visualize.py sim5
python3 visualize.py opcite
python3 visualize.py opmultiome
python3 visualize.py pbmc
python3 visualize.py tea